version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /pratiksha-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /pratiksha-app/docker-credentials/passowrd
    DOCKER_REGISTRY_URL: /pratiksha-app/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r CI-Python-Flask-Service/Python-App/requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - cd CI-Python-Flask-Service/Python-App/
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/python-flask-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/python-flask-app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../Python-App
